### PR TITLE
notify clients when we inline a script tag

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by azakus** [comment]
LGTM

**Comment by nomego** [comment]
Build failure:

```
src/analyzer.ts(371,34): error TS2345: Argument of type '(m1: DocumentDescriptor, m2: DocumentDescriptor) => DocumentDescriptor' is not assignable to parameter of type '(previousValue: DocumentDescriptor, currentValue: Promise<DocumentDescriptor>, currentIndex: numb...'.
  Types of parameters 'm2' and 'currentValue' are incompatible.
    Type 'Promise<DocumentDescriptor>' is not assignable to type 'DocumentDescriptor'.
      Property 'elements' is missing in type 'Promise<DocumentDescriptor>'.
src/analyzer.ts(445,16): error TS2339: Property '__hydrolysisInlined' does not exist on type 'LocNode'.
src/analyzer.ts(567,7): error TS2322: Type 'Promise<DocumentDescriptor>[]' is not assignable to type 'DocumentDescriptor[]'.
  Type 'Promise<DocumentDescriptor>' is not assignable to type 'DocumentDescriptor'.
```

**Comment by garlicnation** [comment]
@nomego That has been addressed w/ the latest push.

**Comment by nomego** [comment]
Well why not carry on with the build reporting? :)

```
src/analyzer.ts(371,34): error TS2345: Argument of type '(m1: DocumentDescriptor, m2: DocumentDescriptor) => DocumentDescriptor' is not assignable to parameter of type '(previousValue: DocumentDescriptor, currentValue: Promise<DocumentDescriptor>, currentIndex: numb...'.
  Types of parameters 'm2' and 'currentValue' are incompatible.
    Type 'Promise<DocumentDescriptor>' is not assignable to type 'DocumentDescriptor'.
      Property 'elements' is missing in type 'Promise<DocumentDescriptor>'.
src/analyzer.ts(567,7): error TS2322: Type 'Promise<DocumentDescriptor>[]' is not assignable to type 'DocumentDescriptor[]'.
  Type 'Promise<DocumentDescriptor>' is not assignable to type 'DocumentDescriptor'.
```

**Pull request merged**
