### PR TITLE
Enabled ES6 parsing for hydrolysis.

### PR DESCRIPTION
**Pull request by brianchin**
Currently Hydrolysis chokes whenever it sees any new syntax for ES6, even though several modern browsers support them already. This PR changes the espree configuration to enable all of its ES6 parsing features it supports.

### CODE REVIEW

**Comment by brianchin** [comment]
This is intended to solve issue #127

**Comment by azakus** [comment]
This looks very similar to #105.

**Comment by brianchin** [comment]
Honestly, either would be fine with me. I ultimately just want the feature. The only thing curious is that #105 seems to fail some test, although that could be strictly historical.

**Comment by garlicnation** [comment]
Recompile, and rebase+squash and I'll merge. Thanks!

**Comment by brianchin** [comment]
Done!

**Pull request merged**
