### PR TITLE
Support for ES6 classes

### PR DESCRIPTION
**Pull request by leodido**
Following from #204.

Initial work. Feedbacks, suggestions very welcome.

cc @garlicnation

### CODE REVIEW

**Comment by RoXuS** [comment]
`enterMethodDefinition` is not setted, I propose this solution to have methods with their annotations.
https://github.com/RoXuS/hydrolysis/blob/es6/src/ast-utils/element-finder.ts#L74

I see two other problems :
- The properties are setted but the jsdoc is not parsed.
- The behaviors doesn't work.

**Comment by garlicnation** [comment]
The biggest thing this needs before any more work is tests. Try to come up with some sample cases and get a few tests failing so that we can cleanly work towards a working implementation.

**Comment by RoXuS** [comment]
Ok I have openned a new PR with test see #230

**Comment by justinfagnani** [comment]
Can't the tests be added to this PR?

**Comment by RoXuS** [comment]
This PR does not work with ES6 classes.
I have lot of js error when I try to see the <iron-component-page> of a composent with this branch.

It is not just the tests.

**Comment by leodido** [comment]
Some considerations follow.

1. Missing support for **factoryImpl** method

    Only used when creating and element with its constructor, not used when element is created by markup or via document.createElement, called after the element initialisation phase (local DOM created, default values set, ...)

2. Missing support for **listeners**

3. Missing support for **extends**

4. Not sure about the use of getters for **observers**.

    Is it better to declare them with a getter ? Or is it better to declare them inside **beforeRegister** with **this.observers** ?
    Same holds for **listeners** and **extends**.

5. Also a **setter** for **behaviors** could be required (used by Polymer to flatten the list/hierarchy of behaviors)

I have created a gist containing a [skeleton ES2015 class for Polymer elements](https://gist.github.com/leodido/8a5aa2b1b3a84e190798).

**Comment by garlicnation** [comment]
@leodido I merged this outside of the PR

**Pull request closed without merging**
